# Generated by Django 3.2.7 on 2021-11-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tienda',
            field=models.CharField(choices=[('Miraflores', 'Miraflores'), ('Tikal Futura', 'Tikal Futura'), ('Eskala Roosevelt', 'Eskala Roosevelt')], default=0, max_length=16),
            preserve_default=False,
        ),
    ]
