# Generated by Django 3.2.7 on 2021-10-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
    ]
