# Generated by Django 3.2.7 on 2021-10-10 04:37

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('ip_addres', models.GenericIPAddressField()),
                ('accion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('foto', models.TextField()),
                ('password', mirage.fields.EncryptedCharField(max_length=255)),
                ('privilegio', models.CharField(choices=[('A', 'Administrador'), ('V', 'Usuario vendedor'), ('R', 'Usuario reporte')], max_length=1)),
            ],
        ),
    ]
