# Generated by Django 3.2.7 on 2021-10-14 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='foto',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(default=1, upload_to='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
