# Generated by Django 3.2.7 on 2021-10-21 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211020_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 18, 57, 54, 800004)),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 18, 57, 54, 800004)),
        ),
    ]
