# Generated by Django 3.2.7 on 2021-11-05 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20211105_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tienda',
            field=models.CharField(choices=[('M', 'Miraflores'), ('T', 'Tikal Futura'), ('E', 'Eskala Roosevelt')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 14, 2, 58, 123185)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 14, 2, 58, 123185)),
        ),
    ]
