# Generated by Django 3.2.7 on 2021-11-07 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_auto_20211106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 21, 32, 15, 347655)),
        ),
        migrations.AlterField(
            model_name='user',
            name='tienda',
            field=models.CharField(choices=[('M', 'Miraflores'), ('T', 'Tikal Futura'), ('E', 'Eskala Roosevelt'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 21, 32, 15, 347655)),
        ),
    ]
