# Generated by Django 3.2.7 on 2021-11-07 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_auto_20211106_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 21, 42, 7, 935259)),
        ),
        migrations.AlterField(
            model_name='user',
            name='privilegio',
            field=models.CharField(choices=[('A', 'Administrador'), ('V', 'Usuario vendedor'), ('R', 'Usuario reporte'), ('U', 'Usuario')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 21, 42, 7, 935761)),
        ),
    ]
