# Generated by Django 3.2.7 on 2021-11-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('POS MOVIL', 'POS MOVIL')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.TextField(blank=True)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
