# Generated by Django 3.2.7 on 2021-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tienda',
            field=models.CharField(choices=[('Miraflores', 'Miraflores'), ('Tikal Futura', 'Tikal Futura'), ('Eskala Roosevelt', 'Eskala Roosevelt')], default=0, max_length=16),
            preserve_default=False,
        ),
    ]
